title: Responsible Computing & Sustainable ICT submission deadlines countdown
description: Countdowns to Responsible Computing & Sustainable ICT submission deadlines. Accepting conferences, workshops and journal deadlines with a focus on responsible use, development, and production of ICT, sustainability aspects of hardware and software, ethics, and policy.
author: Jan Tobias Muehlberg

domain: " responsible-computing .github.io"
baseurl: ""

twitter_username: jtmuehlberg
github_username: responsible-computing
github_repo: responsible-computing 
ga_id:

markdown: kramdown

